# Generated by Django 3.2.8 on 2021-11-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hinhAnh',
            field=models.ImageField(storage='images', upload_to=''),
        ),
    ]
