# Generated by Django 3.2.8 on 2021-11-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_alter_item_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hinhAnh',
            field=models.FileField(upload_to=''),
        ),
    ]
